### PR TITLE
Add the ability to migrate CoreDNS configmap in kubeadm

### PR DESCRIPTION
**Pull request by rajansandeep**
Opened here for reviewing the migration process in Kubeadm
/cc @chrisohaver @fturib

Pending: 
- [x] To add deprecation logs which will be done after https://github.com/coredns/deployment/pull/159 is merged.
- [x] Vendor the migration tool when PR is opened in k/k.
- [x] Add a detailed working/summary of what this PR does when it's opened in k/k

### CODE REVIEW

**Comment by rajansandeep** [comment]
@chrisohaver I have updated the code to include logs and updated the vendoring.
PTAL one last time and I will push this PR to upstream.

**Comment by rajansandeep** [comment]
Kubernetes still maintains a vendor directory and uses the go mod to maintain the vendor for a certain version.
I have followed their guidelines provided: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/vendor.md

**Comment by chrisohaver** [comment]
Looks good, pending "Add a detailed working/summary of what this PR does when it's opened in k/k".

**Comment by rajansandeep** [comment]
@chrisohaver I have added a summary at the end of https://docs.google.com/document/d/18jYC2PmJJZdnmpJDqBzuETJM2VmT8DBzKZJDtAa97Ok/edit#
so that it can be edited easily.

Please take a look to see if it's okay or if changes are required.
Should I open an issue to include this summary and then link the issue to the PR?

**Comment by chrisohaver** [comment]
i made a couple of comments.

**Comment by chrisohaver** [comment]
I would just make the PR... if they ask for an issue to pair it with, you can add it later.

**Pull request merged**
